server:
  port: 7001

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka
  server:
    enable-self-preservation: false